;;;		Copyright (c) William Whitty 2009
;;;
;;;	This file is part of GSL. 
;;;
;;;	GSL is free software: you can redistribute it and/or modify
;;;     it under the terms of the GNU General Public License as published by
;;;     the Free Software Foundation, either version 3 of the License, or
;;;     (at your option) any later version.
;;;
;;;     GSL is distributed in the hope that it will be useful,
;;;     but WITHOUT ANY WARRANTY; without even the implied warranty of
;;;     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;;     GNU General Public License for more details.
;;;
;;;     You should have received a copy of the GNU General Public License
;;;     along with GSL.  If not, see <http://www.gnu.org/licenses/>.

;;--------------------------------------;;
;;	Bit Flags			;;
;;--------------------------------------;;
(in-package :gsl-gl)

(const +GL-ZERO+				#x0000)
(const +GL-ONE+					#x0001)

;;	MATRIX BIT FLAGS	;;;;{{{
(const +GL-MATRIX-MODE+				#x00BA0)
(const +GL-MODELVIEW+				#x01700)
(const +GL-PROJECTION+				#x01701)
(const +GL-TEXTURE+				#x01702)
;;}}}

;;	DEPTH AND BLENDING	;;;;{{{
(const +GL-NEVER+				#x0200)
(const +GL-LESS+				#x0201)
(const +GL-EQUAL+				#x0202)
(const +GL-LEQUAL+				#x0203)
(const +GL-GREATER+				#x0204)
(const +GL-NOTEQUAL+				#x0205)
(const +GL-GEQUAL+				#x0206)
(const +GL-ALWAYS+				#x0207)
(const +GL-DEPTH-TEST+				#x0B71)
(const +GL-DEPTH-BITS+				#x0D56)
(const +GL-DEPTH-CLEAR-VALUE+			#x0B73)
(const +GL-DEPTH-FUNC+				#x0B74)
(const +GL-DEPTH-RANGE+				#x0B70)
(const +GL-DEPTH-WRITEMASK+			#x0B72)
(const +GL-DEPTH-COMPONENT+			#x1902)
(const +GL-BLEND+				#x0BE2)
(const +GL-BLEND-SRC+				#x0BE1)
(const +GL-BLEND-DST+				#x0BE0)
(const +GL-SRC-COLOR+				#x0300)
(const +GL-ONE-MINUS-SRC-COLOR+			#x0301)
(const +GL-SRC-ALPHA+				#x0302)
(const +GL-ONE-MINUS-SRC-ALPHA+			#x0303)
(const +GL-DST-ALPHA+				#x0304)
(const +GL-ONE-MINUS-DST-ALPHA+			#x0305)
(const +GL-DST-COLOR+				#x0306)
(const +GL-ONE-MINUS-DST-COLOR+			#x0307)
(const +GL-SRC-ALPHA-SATURATE+			#x0308)
;;}}}

;;	ATTRIBUTE BIT FLAGS	;;;;{{{
(const +GL-CURRENT-BIT+				#x00001)
(const +GL-POINT-BIT+				#x00002)
(const +GL-LINE-BIT+				#x00004)
(const +GL-POLYGON-BIT+				#x00008)
(const +GL-POLYGON-STIPPLE-BIT+			#x00010)
(const +GL-PIXEL-MODE-BIT+			#x00020)
(const +GL-LIGHTING-BIT+			#x00040)
(const +GL-FOG-BIT+				#x00080)
(const +GL-DEPTH-BUFFER-BIT+			#x00100)
(const +GL-ACCUM-BUFFER-BIT+			#x00200)
(const +GL-STENCIL-BUFFER-BIT+			#x00400)
(const +GL-VIEWPORT-BIT+			#x00800)
(const +GL-TRANSFORM-BIT+			#x01000)
(const +GL-ENABLE-BIT+				#x02000)
(const +GL-COLOR-BUFFER-BIT+			#x04000)
(const +GL-HINT-BIT+				#x08000)
(const +GL-EVAL-BIT+				#x10000)
(const +GL-LIST-BIT+				#x20000)
(const +GL-TEXTURE-BIT+				#x40000)
(const +GL-SCISSOR-BIT+				#x80000)
(const +GL-ALL-ATTRIB-BITS+			#xFFFFF)
;;}}}

;;	PRIMITIVE BIT FLAGS	;;;;{{{
(const +GL-POINTS+				#x00000)
(const +GL-LINES+				#x00001)
(const +GL-LINE-LOOP+				#x00002)
(const +GL-LINE-STRIP+				#x00003)
(const +GL-TRIANGLES+				#x00004)
(const +GL-TRIANGLE-STRIP+			#x00005)
(const +GL-TRIANGLE-FAN+			#x00006)
(const +GL-QUADS+				#x00007)
(const +GL-QUAD-STRIP+				#x00008)
(const +GL-POLYGON+				#x00009)
;;}}}

;;	STENCIL TEST BIT FLAGS	;;;;{{{
(const +GL-STENCIL-BITS+			#x0D57)
(const +GL-STENCIL-TEST+			#x0B90)
(const +GL-STENCIL-CLEAR-VALUE+			#x0B91)
(const +GL-STENCIL-FUNC+			#x0B92)
(const +GL-STENCIL-VALUE-MASK+			#x0B93)
(const +GL-STENCIL-FAIL+			#x0B94)
(const +GL-STENCIL-PASS-DEPTH-FAIL+		#x0B95)
(const +GL-STENCIL-PASS-DEPTH-PASS+		#x0B96)
(const +GL-STENCIL-REF+				#x0B97)
(const +GL-STENCIL-WRITEMASK+			#x0B98)
(const +GL-STENCIL-INDEX+			#x1901)
(const +GL-KEEP+				#x1E00)
(const +GL-REPLACE+				#x1E01)
(const +GL-INCR+				#x1E02)
(const +GL-DECR+				#x1E03)
;;}}}

;;	TEXTURE MAPPING BITS	;; ;;{{{
(const +GL-TEXTURE-ENV+				#x2300)
(const +GL-TEXTURE-ENV-MODE+			#x2200)
(const +GL-TEXTURE-1D+				#x0DE0)
(const +GL-TEXTURE-2D+				#x0DE1)
(const +GL-TEXTURE-WRAP-S+			#x2802)
(const +GL-TEXTURE-WRAP-T+			#x2803)
(const +GL-TEXTURE-MAG-FILTER+			#x2800)
(const +GL-TEXTURE-MIN-FILTER+			#x2801)
(const +GL-TEXTURE-ENV-COLOR+			#x2201)
(const +GL-TEXTURE-GEN-S+			#x0C60)
(const +GL-TEXTURE-GEN-T+			#x0C61)
(const +GL-TEXTURE-GEN-MODE+			#x2500)
(const +GL-TEXTURE-BORDER-COLOR+		#x1004)
(const +GL-TEXTURE-WIDTH+			#x1000)
(const +GL-TEXTURE-HEIGHT+			#x1001)
(const +GL-TEXTURE-BORDER+			#x1005)
(const +GL-TEXTURE-COMPONENTS+			#x1003)
(const +GL-TEXTURE-RED-SIZE+			#x805C)
(const +GL-TEXTURE-GREEN-SIZE+			#x805D)
(const +GL-TEXTURE-BLUE-SIZE+			#x805E)
(const +GL-TEXTURE-ALPHA-SIZE+			#x805F)
(const +GL-TEXTURE-LUMINANCE-SIZE+		#x8060)
(const +GL-TEXTURE-INTENSITY-SIZE+		#x8061)
(const +GL-NEAREST-MIPMAP-NEAREST+		#x2700)
(const +GL-NEAREST-MIPMAP-LINEAR+		#x2702)
(const +GL-LINEAR-MIPMAP-NEAREST+		#x2701)
(const +GL-LINEAR-MIPMAP-LINEAR+		#x2703)
(const +GL-OBJECT-LINEAR+			#x2401)
(const +GL-OBJECT-PLANE+			#x2501)
(const +GL-EYE-LINEAR+				#x2400)
(const +GL-EYE-PLANE+				#x2502)
(const +GL-SPHERE-MAP+				#x2402)
(const +GL-DECAL+				#x2101)
(const +GL-MODULATE+				#x2100)
(const +GL-NEAREST+				#x2600)
(const +GL-REPEAT+				#x2901)
(const +GL-CLAMP+				#x2900)
(const +GL-S+					#x2000)
(const +GL-T+					#x2001)
(const +GL-R+					#x2002)
(const +GL-Q+					#x2003)
(const +GL-TEXTURE-GEN-R+			#x0C62)
(const +GL-TEXTURE-GEN-Q+			#x0C63)
;;}}}

;;	FRAMEBUFFER BIT FLAGS	;;;;{{{
(const +GL-INVALID-FRAMEBUFFER-OPERATION+                   #x0506)
(const +GL-FRAMEBUFFER-ATTACHMENT-COLOR-ENCODING+           #x8210)
(const +GL-FRAMEBUFFER-ATTACHMENT-COMPONENT-TYPE+           #x8211)
(const +GL-FRAMEBUFFER-ATTACHMENT-RED-SIZE+                 #x8212)
(const +GL-FRAMEBUFFER-ATTACHMENT-GREEN-SIZE+               #x8213)
(const +GL-FRAMEBUFFER-ATTACHMENT-BLUE-SIZE+                #x8214)
(const +GL-FRAMEBUFFER-ATTACHMENT-ALPHA-SIZE+               #x8215)
(const +GL-FRAMEBUFFER-ATTACHMENT-DEPTH-SIZE+               #x8216)
(const +GL-FRAMEBUFFER-ATTACHMENT-STENCIL-SIZE+             #x8217)
(const +GL-FRAMEBUFFER-DEFAULT+                             #x8218)
(const +GL-FRAMEBUFFER-UNDEFINED+                           #x8219)
(const +GL-DEPTH-STENCIL-ATTACHMENT+                        #x821A)
(const +GL-INDEX+                                           #x8222)
(const +GL-MAX-RENDERBUFFER-SIZE+                           #x84E8)
(const +GL-DEPTH-STENCIL+                                   #x84F9)
(const +GL-UNSIGNED-INT-24-8+                               #x84FA)
(const +GL-DEPTH24-STENCIL8+                                #x88F0)
(const +GL-TEXTURE-STENCIL-SIZE+                            #x88F1)
(const +GL-FRAMEBUFFER-BINDING+                             #x8CA6)
(const +GL-RENDERBUFFER-BINDING+                            #x8CA7)
(const +GL-READ-FRAMEBUFFER+                                #x8CA8)
(const +GL-DRAW-FRAMEBUFFER+                                #x8CA9)
(const +GL-READ-FRAMEBUFFER-BINDING+                        #x8CAA)
(const +GL-RENDERBUFFER-SAMPLES+                            #x8CAB)
(const +GL-FRAMEBUFFER-ATTACHMENT-OBJECT-TYPE+              #x8CD0)
(const +GL-FRAMEBUFFER-ATTACHMENT-OBJECT-NAME+              #x8CD1)
(const +GL-FRAMEBUFFER-ATTACHMENT-TEXTURE-LEVEL+            #x8CD2)
(const +GL-FRAMEBUFFER-ATTACHMENT-TEXTURE-CUBE-MAP-FACE+    #x8CD3)
(const +GL-FRAMEBUFFER-ATTACHMENT-TEXTURE-LAYER+            #x8CD4)
(const +GL-FRAMEBUFFER-COMPLETE+                            #x8CD5)
(const +GL-FRAMEBUFFER-INCOMPLETE-ATTACHMENT+               #x8CD6)
(const +GL-FRAMEBUFFER-INCOMPLETE-MISSING-ATTACHMENT+       #x8CD7)
(const +GL-FRAMEBUFFER-INCOMPLETE-DRAW-BUFFER+              #x8CDB)
(const +GL-FRAMEBUFFER-INCOMPLETE-READ-BUFFER+              #x8CDC)
(const +GL-FRAMEBUFFER-UNSUPPORTED+                         #x8CDD)
(const +GL-MAX-COLOR-ATTACHMENTS+                           #x8CDF)
(const +GL-COLOR-ATTACHMENT0+                               #x8CE0)
(const +GL-COLOR-ATTACHMENT1+                               #x8CE1)
(const +GL-COLOR-ATTACHMENT2+                               #x8CE2)
(const +GL-COLOR-ATTACHMENT3+                               #x8CE3)
(const +GL-COLOR-ATTACHMENT4+                               #x8CE4)
(const +GL-COLOR-ATTACHMENT5+                               #x8CE5)
(const +GL-COLOR-ATTACHMENT6+                               #x8CE6)
(const +GL-COLOR-ATTACHMENT7+                               #x8CE7)
(const +GL-COLOR-ATTACHMENT8+                               #x8CE8)
(const +GL-COLOR-ATTACHMENT9+                               #x8CE9)
(const +GL-COLOR-ATTACHMENT10+                              #x8CEA)
(const +GL-COLOR-ATTACHMENT11+                              #x8CEB)
(const +GL-COLOR-ATTACHMENT12+                              #x8CEC)
(const +GL-COLOR-ATTACHMENT13+                              #x8CED)
(const +GL-COLOR-ATTACHMENT14+                              #x8CEE)
(const +GL-COLOR-ATTACHMENT15+                              #x8CEF)
(const +GL-DEPTH-ATTACHMENT+                                #x8D00)
(const +GL-STENCIL-ATTACHMENT+                              #x8D20)
(const +GL-FRAMEBUFFER+                                     #x8D40)
(const +GL-RENDERBUFFER+                                    #x8D41)
(const +GL-RENDERBUFFER-WIDTH+                              #x8D42)
(const +GL-RENDERBUFFER-HEIGHT+                             #x8D43)
(const +GL-RENDERBUFFER-INTERNAL-FORMAT+                    #x8D44)
(const +GL-STENCIL-INDEX1+                                  #x8D46)
(const +GL-STENCIL-INDEX4+                                  #x8D47)
(const +GL-STENCIL-INDEX8+                                  #x8D48)
(const +GL-STENCIL-INDEX16+                                 #x8D49)
(const +GL-RENDERBUFFER-RED-SIZE+                           #x8D50)
(const +GL-RENDERBUFFER-GREEN-SIZE+                         #x8D51)
(const +GL-RENDERBUFFER-BLUE-SIZE+                          #x8D52)
(const +GL-RENDERBUFFER-ALPHA-SIZE+                         #x8D53)
(const +GL-RENDERBUFFER-DEPTH-SIZE+                         #x8D54)
(const +GL-RENDERBUFFER-STENCIL-SIZE+                       #x8D55)
(const +GL-FRAMEBUFFER-INCOMPLETE-MULTISAMPLE+              #x8D56)
(const +GL-MAX-SAMPLES+                                     #x8D57)
;;}}}
